apiVersion: v1
kind: Service
metadata:
  name: jpress
spec:
  selector:
    app: jpress
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jpress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jpress
    spec:
      containers:
      - name: jpress
        image: siji/jpress:1.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: jpress-mariadb-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: jpress-mariadb-credentials
              key: port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: jpress-mariadb-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: jpress-mariadb-credentials
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: jpress-mariadb-credentials
              key: database
